import type { State, PresetName } from "./state";

type PresetPatch = Partial<Omit<State, "preset">>;

export const PRESETS: Record<PresetName, PresetPatch> = {
  Aurora: {
    count: 120_000,
    size: 2.4,
    sizeJitter: 0.45,
    colorA: "#7af7c8",
    colorB: "#9c5cff",
    gradientMode: "velocity",
    bgColorTop: "#021024",
    bgColorBottom: "#063d2f",
    curlStrength: 1.1,
    curlScale: 1.2,
    timeScale: 0.7,
    mouseForce: 0.5,
    bloomStrength: 0.7,
    bloomThreshold: 0.35,
    bloomRadius: 0.9,
  },
  Plasma: {
    count: 90_000,
    size: 3.2,
    sizeJitter: 0.55,
    colorA: "#ff5edf",
    colorB: "#ffcf2b",
    gradientMode: "velocity",
    bgColorTop: "#1a0030",
    bgColorBottom: "#2b0040",
    curlStrength: 1.4,
    curlScale: 1.6,
    timeScale: 1.2,
    mouseForce: 0.9,
    bloomStrength: 0.85,
    bloomThreshold: 0.3,
    bloomRadius: 1.0,
  },
  Constellation: {
    count: 40_000,
    size: 1.6,
    sizeJitter: 0.7,
    colorA: "#ffffff",
    colorB: "#a0c4ff",
    gradientMode: "age",
    bgColorTop: "#000010",
    bgColorBottom: "#0a0a2a",
    curlStrength: 0.35,
    curlScale: 0.6,
    timeScale: 0.4,
    mouseForce: 0.2,
    bloomStrength: 0.55,
    bloomThreshold: 0.55,
    bloomRadius: 0.6,
  },
  Inkwell: {
    count: 180_000,
    size: 1.4,
    sizeJitter: 0.3,
    colorA: "#0a0a0a",
    colorB: "#ff4d4d",
    gradientMode: "position",
    bgColorTop: "#f4f1ec",
    bgColorBottom: "#e8e2d6",
    curlStrength: 1.6,
    curlScale: 1.8,
    timeScale: 0.9,
    mouseForce: -0.6,
    bloomStrength: 0.15,
    bloomThreshold: 0.85,
    bloomRadius: 0.4,
  },
  Nebula: {
    count: 200_000,
    size: 2.8,
    sizeJitter: 0.6,
    colorA: "#3d5cff",
    colorB: "#ff3d8b",
    gradientMode: "position",
    bgColorTop: "#100018",
    bgColorBottom: "#001830",
    curlStrength: 0.9,
    curlScale: 0.9,
    timeScale: 0.5,
    mouseForce: 0.4,
    bloomStrength: 1.0,
    bloomThreshold: 0.25,
    bloomRadius: 1.2,
  },
};
